/**
 * stardust/scripts/eds/encoders.mjs — ENCODE: replica prototype module root → DA section HTML (stardust:rollout Phase C).
 * Input vocabulary = the replica prototypes (stardust/prototypes/*-proposed.html, generated by scripts/replica/author.mjs).
 * David's Model: prose is DEFAULT CONTENT; one block per designed repeating/bespoke module; CTAs as emphasis-marked links
 * (strong = primary Vann pill, em = secondary outline, em+strong = green action); images stay on the public DAM origin.
 * Each encoder returns { html, blocks: [names] } or null (converter falls back to prose + logs a gap).
 * Block set (locked in stardust/eds-conversion-log.md): breadcrumbs · bank-choice · columns · cards (grid|price|news|nav|small)
 * · banner · accordion (faq) · feedback · calculator · shortcuts · callout · cobranding · table (native) · header · footer.
 */
import * as L from './lib.mjs';

const { esc, href, inline, prose, ctaHtml, imgHtml, pic, block, section, heading } = L;
const q = (el, s) => el?.querySelector(s) || null;
const qa = (el, s) => (el ? [...el.querySelectorAll(s)] : []);
const cls = (el) => (el?.getAttribute('class') || '').split(/\s+/).filter(Boolean);
export const bandBg = (el) => { const m = (el?.getAttribute('style') || '').match(/--band-bg:\s*([^;]+)/i); return m ? m[1].trim().toLowerCase() : null; };
export const bgToken = (hex) => ({ '#fdf8f5': 'sand', '#faf0e7': 'sand-70', '#f8e9dd': 'sand', '#d8e9f2': 'frost', '#005aa4': 'brand', '#ffffff': null, '#fff': null }[hex] ?? null);
export const styleOf = (...tokens) => tokens.filter(Boolean).join(', ');

/** Default-content prose from a .richtext (or any container): verbatim inline markup, CTAs as emphasis links. */
export function richtext(el, ctx) {
  if (!el) return '';
  let out = '';
  for (const n of el.childNodes) {
    if (n.nodeType === 3) { if (n.textContent.trim()) out += `<p>${esc(n.textContent.trim())}</p>`; continue; }
    if (n.nodeType !== 1) continue;
    const t = n.tagName.toLowerCase();
    if (t === 'div' && /\b(button-wrap|button-list)\b/.test(n.className)) { out += qa(n, 'a.btn, button.btn').map((a) => (a.tagName === 'A' ? ctaHtml(a, ctx) : `<p>${inline(q(a, '.btn__label') || a, ctx)}</p>`)).join(''); continue; }
    if (t === 'div' && /\bimage\b/.test(n.className)) { const img = q(n, 'img'); if (img) out += pic(img, ctx); continue; }
    if (t === 'div' && /\brichtext\b/.test(n.className)) { out += richtext(n, ctx); continue; }
    if (t === 'div' && /\bcard\b/.test(n.className)) { out += cardRows([n], ctx).map((r) => r.map((c) => c).join('')).join(''); continue; }
    if (t === 'a' && /\bbtn\b/.test(n.className)) { out += ctaHtml(n, ctx); continue; }
    if (/^h[1-6]$/.test(t)) { const ht = L.headingTag(n); out += `<${ht}>${inline(n, ctx)}</${ht}>`; continue; }
    out += prose({ childNodes: [n] }, ctx);
  }
  return out;
}

/** Card → one DA row: [media?][body: tag p (uppercase eyebrow as <p><em>? no — plain p), title heading-link, text p]. */
export function cardRows(cards, ctx) {
  return cards.map((card) => {
    const img = q(card, '.card__media img, .card__iconwrap img');
    const title = q(card, '.card__title'); const tag = q(card, '.card__tag'); const texts = qa(card, '.card__text');
    const hrefV = title?.tagName === 'A' ? href(title.getAttribute('href') || '') : '';
    const lvl = card.closest('.card-list--news, .newsfeed') ? 'h3' : 'h3';
    let body = '';
    if (tag) body += `<p>${inline(tag, ctx)}</p>`;
    if (title) body += hrefV ? `<${lvl}><a href="${esc(hrefV)}">${inline(title, ctx)}</a></${lvl}>` : `<${lvl}>${inline(title, ctx)}</${lvl}>`;
    for (const p of texts) body += `<p>${inline(p, ctx)}</p>`;
    return [img ? pic(img, ctx) : '', body]; // always [media][body] so every row has the same shape (lint D3); an image-less card has an empty media cell
  });
}
export const cardVariant = (list) => { const c = cls(list); if (c.includes('card-list--price')) return 'price'; if (c.includes('card-list--visual-nav')) return 'nav'; if (c.includes('card-list--static-cards')) return 'static'; return null; };

/* ------------------------------------------------------------------ chrome-adjacent ------------------------------------------------------------------ */
export function breadcrumb(root, ctx) {
  ctx.notes.push('lint D1 breadcrumbs: bespoke navigation widget (nav landmark, chevron separators, current-page state) — not default content');
  const a = q(root, 'a'); if (!a) return null;
  return { html: section([block('breadcrumbs', [], [[`<p><a href="${esc(href(a.getAttribute('href') || ''))}">${esc(a.textContent.trim())}</a></p>`]])]), blocks: ['breadcrumbs'] };
}
/** bank-choice band (fixed composition, template-slotted): rows = heading | lede | label+placeholder | position label | expand label | one row per bank (link + tagline). */
export function bankChoice(root, ctx) {
  ctx.notes.push('lint D3 bank-choice: rows are role-shaped by position (heading, sublead, [label][placeholder], position button, expand button, [bank link][tagline]×N) — the block reads them positionally');
  const rows = [
    [`<p>${inline(q(root, '.bank-choice__heading'), ctx)}</p>`],
    [`<p>${inline(q(root, '.bank-choice__sublead'), ctx)}</p>`],
    [`<p>${esc(q(root, '.bank-choice__label')?.textContent.trim() || 'Ditt postnummer')}</p>`, `<p>${esc(q(root, '.bank-choice__input')?.getAttribute('placeholder') || 'Postnummer')}</p>`],
    [`<p>${esc([...(q(root, '.bank-choice__position-btn .btn__label')?.childNodes || [])].filter((n) => n.nodeType === 3).map((n) => n.data).join('').trim() || 'Bruk min posisjon')}</p>`],
    [`<p>${esc(q(root, '.bank-choice__expand .btn__label')?.textContent.trim() || 'Se alle banker')}</p>`],
    ...qa(root, '.bank-choice__bank').map((li) => { const a = q(li, 'a'); return [`<p><a href="${esc(href(a.getAttribute('href') || ''))}">${inline(a, ctx)}</a></p>`, `<p>${esc(q(li, '.bank-choice__bank-tagline')?.textContent.trim() || '')}</p>`]; }),
  ];
  return { html: section([block('bank-choice', [], rows)]), blocks: ['bank-choice'] };
}

/* ------------------------------------------------------------------ bands / columns / cards ------------------------------------------------------------------ */
/** A .band (background-container) or a top-level .cols: one DA section per band; each grid row → columns block or cards block; a single centred heading row → default content. */
export function band(root, ctx, opts = {}) {
  const tint = bgToken(bandBg(root) || bandBg(q(root, '.cols')));
  const rows = qa(root, '.grid-row'); const parts = []; const blocks = [];
  let extraStyle = opts.topLevelCols ? 'cols' : 'band';
  for (const row of rows) {
    const cols = qa(row, ':scope > .col');
    const cards = cols.filter((c) => q(c, ':scope > .col__content > .card'));
    if (cards.length && cards.length === cols.length) { // card grid row
      const span = (cls(cols[0]).find((c) => /^col-lg-\d+$/.test(c)) || 'col-lg-3').replace('col-', '');
      parts.push(block('cards', ['grid', span], cardRows(cols.map((c) => q(c, '.card')), ctx))); blocks.push('cards'); continue;
    }
    if (cols.length === 1 && /grid-row--cols-/.test(row.className)) { parts.push(richtext(q(cols[0], '.col__content'), ctx)); continue; } // centred heading row → default content
    // text / image columns → columns block, one row, one cell per column; variants carry the span/offset model
    const variants = cols.map((c) => { const k = cls(c); const span = (k.find((x) => /^col-lg-\d+$/.test(x)) || 'col-lg-12').replace('col-', ''); const off = k.find((x) => /^col-lg-offset-\d+$/.test(x)); const first = k.includes('col--first') ? 'first' : null; const align = (k.find((x) => /^col--(middle|center|bottom)$/.test(x)) || '').replace('col--', ''); return [span, off ? off.replace('col-lg-offset-', 'offset-') : null, first, align].filter(Boolean).join('-'); });
    const cells = cols.map((c) => richtext(q(c, ':scope > .col__content'), ctx));
    if (q(row, '.lead-blue')) variants.push('lead');
    parts.push(block('columns', variants, [cells])); blocks.push('columns');
  }
  // non-grid children of a band (rule, banner-small, richtext) → follow in the same section
  for (const ch of [...root.children].flatMap((c) => (c.classList.contains('band__content') ? [...c.children] : [c]))) {
    if (ch.classList.contains('cols') || ch.classList.contains('grid-row')) continue;
    if (ch.tagName === 'HR') { extraStyle = styleOf(extraStyle, /rule--extra-top/.test(ch.className) ? 'rule-after' : null); continue; }
    const enc = ENCODERS[[...ch.classList].find((c) => ENCODERS[c])]; if (enc) { const r = enc(ch, ctx, { inline: true }); if (r) { parts.push(r.html); blocks.push(...r.blocks); } continue; }
    if (ch.classList.contains('richtext')) parts.push(richtext(ch, ctx));
  }
  return { html: section(parts, { style: styleOf(extraStyle, tint) }), blocks: [...new Set(blocks)] };
}
export const cols = (root, ctx) => band(root, ctx, { topLevelCols: true });

export function bannerSmall(root, ctx, opts = {}) {
  const color = (cls(root).find((c) => /^banner-small--color\d$/.test(c)) || '').replace('banner-small--', '');
  const img = q(root, '.banner-small__media img');
  const body = `${heading(q(root, '.banner-small__heading'), ctx)}${q(root, '.banner-small__info') ? `<p>${inline(q(root, '.banner-small__info'), ctx)}</p>` : ''}${qa(root, '.banner-small__bottom a.btn').map((a) => ctaHtml(a, ctx)).join('')}`;
  const html = block('banner', [color].filter(Boolean), [[img ? pic(img, ctx) : '', body]]);
  return { html: opts.inline ? html : section([html]), blocks: ['banner'] };
}

export function prices(root, ctx) {
  const tint = bgToken(bandBg(root)) || 'sand';
  const parts = [richtext(q(root, '.prices__title'), ctx), block('cards', ['price'], cardRows(qa(root, '.card-list .card'), ctx)), richtext(q(root, '.prices__bottom'), ctx)];
  return { html: section(parts, { style: styleOf('prices', tint) }), blocks: ['cards'] };
}

export function richtextSection(root, ctx) {
  return { html: section([richtext(root, ctx)], { style: 'center, narrow, gap-72' }), blocks: [] };
}

export function calculator(root, ctx) {
  ctx.notes.push('lint D1 calculator: bespoke widget (shadow-root snapshot of the loan calculator; dynamics #7 interim) — the link names the snapshot');
  const snap = ctx.slug.replace(/^nb-bank-/, '').replace(/-html$/, '');
  ctx.notes.push(`calculator: static snapshot served from /data/calculator/${snap}.html (dynamics #7 interim — computation disabled until the API is exposed)`);
  return { html: section([block('calculator', [], [[`<p><a href="/data/calculator/${snap}.html">Boliglånskalkulator</a></p>`]])]), blocks: ['calculator'] };
}

export function faq(root, ctx) {
  const items = qa(root, '.accordion__item');
  const visible = items.filter((it) => !/display:\s*none/.test(it.getAttribute('style') || '')).length;
  const rows = items.map((it) => {
    const qEl = q(it, '.accordion__label'); const body = q(it, '.accordion__body');
    let answer = '';
    for (const ch of body?.children || []) {
      if (ch.classList.contains('feedback')) continue; // per-item "Var dette nyttig?" is block-owned UI
      if (ch.classList.contains('accordion__link')) { answer += `<p><a href="${esc(href(ch.getAttribute('href') || ''))}">${esc(q(ch, '.visually-hidden')?.textContent.trim() || 'Les mer')}</a></p>`; continue; }
      answer += richtext(ch, ctx);
    }
    return [`<p>${inline(qEl, ctx)}</p>`, answer];
  });
  const more = q(root, '.faq__more-btn .btn__label');
  const parts = [richtext(q(root, '.faq__title'), ctx), block('accordion', ['faq', visible < items.length ? `show-${visible}` : null].filter(Boolean), rows)];
  if (more) parts.push(`<p>${esc(more.textContent.trim())}</p>`);
  return { html: section(parts, { style: 'faq, gap-48' }), blocks: ['accordion'] };
}

export function relatedTopics(root, ctx) {
  const parts = [richtext(q(root, '.related-topics__title, .related-products__title'), ctx), block('cards', ['news'], cardRows(qa(root, '.newsfeed .card'), ctx))];
  const btn = q(root, '.button-wrap a.btn'); if (btn) parts.push(ctaHtml(btn, ctx));
  const tint = bgToken(bandBg(root));
  return { html: section(parts, { style: styleOf('related', 'gap-48', tint) }), blocks: ['cards'] };
}
export const relatedProducts = relatedTopics;

export function feedback(root, ctx) {
  ctx.notes.push('lint D1 feedback: interactive widget (thumbs up/down, thanks state; dynamics #5 interim) — the row carries its question only');
  const qEl = q(root, '.feedback__question');
  const qt = qEl && /^h[1-6]$/i.test(qEl.tagName) ? qEl.tagName.toLowerCase() : 'p'; // the live question is an h2 — keep its rank
  return { html: section([block('feedback', [], [[`<${qt}>${inline(qEl, ctx)}</${qt}>`]])], { style: 'gap-48' }), blocks: ['feedback'] };
}

export function reference(root, ctx) {
  return { html: section([richtext(q(root, '.richtext') || root, ctx)], { style: 'reference, center, rule-visible' }), blocks: [] };
}

/* ------------------------------------------------------------------ hub modules ------------------------------------------------------------------ */
export function cardList(root, ctx) { // visual-nav / static-cards / card-list sections
  const list = q(root, '.card-list') || root;
  const parts = [richtext(q(root, '[class$="__title"]'), ctx), block('cards', [cardVariant(list)].filter(Boolean), cardRows(qa(list, '.card'), ctx))];
  return { html: section(parts, { style: styleOf('gap-48', bgToken(bandBg(root))) }), blocks: ['cards'] };
}
export function shortcuts(root, ctx) {
  const parts = [heading(q(root, 'h2'), ctx), `<ul>${qa(root, '.shortcuts__link').map((a) => `<li><a href="${esc(href(a.getAttribute('href') || ''))}">${inline(a, ctx)}</a></li>`).join('')}</ul>`];
  return { html: section([block('shortcuts', [], [[parts.join('')]])], { style: 'gap-72' }), blocks: ['shortcuts'] };
}
export function tip(root, ctx) {
  return { html: section([block('callout', ['tip'], [[richtext(root, ctx)]])], { style: 'gap-48' }), blocks: ['callout'] };
}
export function usp(root, ctx) {
  // one row per item: [icon][text]; the illustrated (icon-list) variant carries the live layout token
  const items = qa(root, '.usp__item'); if (!items.length) { ctx.notes.push('usp: live module rendered no items (client-side) — nothing authored'); return null; }
  const rows = items.map((it) => { const ic = q(it, '.usp__icon img'); const sv = q(it, '.usp__icon svg'); const icon = ic ? pic(ic, ctx) : sv ? `<p>${L.iconOf(sv)}</p>` : ''; const rest = { childNodes: [...it.childNodes].filter((n) => !(n.nodeType === 1 && n.classList.contains('usp__icon'))) }; return [icon, richtext(rest, ctx) || prose(rest, ctx)]; });
  return { html: section([block('usp', root.classList.contains('usp--icons-left') ? ['illustrated'] : [], rows)]), blocks: ['usp'] };
}
export function moduleFallback(root, ctx) { // unknown module → prose default content + gap
  const html = richtext(root, ctx); if (!html.trim()) return null; ctx.gaps.push(`module ${cls(root).join('.')} emitted as prose`);
  return { html: section([html]), blocks: [] };
}

export const ENCODERS = {
  breadcrumb, 'bank-choice': bankChoice, band, cols, 'banner-small': bannerSmall, prices, richtext: richtextSection, calculator, faq,
  'related-topics': relatedTopics, 'related-products': relatedProducts, feedback, reference, 'visual-nav': cardList, 'static-cards': cardList, 'card-list': cardList,
  shortcuts, tip, usp, module: moduleFallback,
};
